In [18]:
import numpy as np
import torch
from importlib import reload
import math
import sys
sys.path.append("/home/wu/Ubuntu/series_kinematics/")
import help as hp
reload(hp)
pi = torch.pi
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

In [ ]:
DH参数表

| $\alpha_{i-1}$ | $a_{i-1}$ | $d_i$ | $\theta_i$ |
| -------------- | --------- | ----- | ---------- |
| 0              | 0         | 0     | $\theta_1$ |
| $-\frac{\pi}{2}$      | 0         | 0     | $\theta_2$ |
| 0              | $a_2$     | $d_3$ | $\theta_3$ |
| $-\frac{\pi}{2}$      | $a_3$     | $d_4$ | $\theta_4$ |
| $\frac{\pi}{2}$       | 0         | 0     | $\theta_5$ |
| $-\frac{\pi}{2}$      | 0         | 0     | $\theta_6$ |

In [14]:
#forward
Thetas= torch.tensor([pi/4,-pi/2,+pi/3,-pi/2,-pi/4,pi/2],device=device)
T_0 = torch.tensor([0,0,0,Thetas[0]],device =device)
T_1 = torch.tensor([-pi/2,0,0,Thetas[1]],device =device)
T_2 = torch.tensor([0,0.5,0.1,Thetas[2]],device =device)
T_3 = torch.tensor([-pi/2,0.35,0.08,Thetas[3]],device =device)
T_4 = torch.tensor([pi/2,0,0,Thetas[4]],device =device)
T_5 = torch.tensor([-pi/2,0,0,Thetas[5]],device =device)
T_ori = hp.Series_forward(T_0,T_1,T_2,T_3,T_4,T_5).forward()
Thetas

tensor([ 0.7854, -1.5708,  1.0472, -1.5708, -0.7854,  1.5708], device='cuda:0')

In [15]:
T_ori

tensor([[ 0.6124,  0.7500, -0.2500,  0.1719],
        [ 0.6124, -0.2500,  0.7500,  0.3133],
        [ 0.5000, -0.6124, -0.6124,  0.6057],
        [ 0.0000,  0.0000,  0.0000,  1.0000]], device='cuda:0')

In [16]:
hp.Trans_matrix(T_0[0],T_0[1],T_0[2],T_0[3]).trans_matrix()

tensor([[ 0.7071, -0.7071,  0.0000,  0.0000],
        [ 0.7071,  0.7071,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  1.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  1.0000]], device='cuda:0')

In [17]:
#bacward solver of 8 Thetas theta
Solutions = hp.Solver(T_ori,T_0[:3],T_1[:3],T_2[:3],T_3[:3],T_4[:3],T_5[:3]).solver()
Solutions

tensor([[ 0.7854, -1.5708,  1.0472,  1.5708,  0.7854, -1.5708],
        [ 0.7854, -0.5400, -1.4966,  0.7862,  1.5300, -0.0409],
        [-1.7890, -2.6016,  1.0472, -0.5777,  2.3022, -3.0180],
        [-1.7890, -1.5708, -1.4966, -2.5693,  2.2929,  0.9369],
        [ 0.7854, -1.5708,  1.0472, -1.5708, -0.7854,  1.5708],
        [ 0.7854, -0.5400, -1.4966, -2.3554, -1.5300,  3.1007],
        [-1.7890, -2.6016,  1.0472,  2.5639, -2.3022,  0.1236],
        [-1.7890, -1.5708, -1.4966,  0.5723, -2.2929, -2.2047]],
       device='cuda:0')